version: '3.9'

volumes:
  postgres_data:
  static_volume:

networks:
  db_net:

services:
  db:
    image: postgres:15-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./logs:/var/log
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready - U admin_django -d widget_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
    - 5432:5432
    env_file:
      - .env



