version: '3.9'

volumes:
  postgres_data:
  static_volume:

networks:
  db_net:

services:
  web:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    volumes:
    - .:/src/
    - static_volume:/src/staticfiles
    networks:
      - db_net
    ports:
    - 8000:8000
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./logs:/var/log
    - .:/docker-entrypoint-initdb.d
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready - U admin_django -d widget_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
    - 5432:5432
    env_file:
      - .env
  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
    - static_volume:/src/staticfiles
    networks:
      - db_net
    ports:
    - 80:80
    depends_on:
      - web



